import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "en" | "ru";

interface LanguageState {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.catalog": "Catalog",
    "nav.products": "Products",
    "nav.store": "Store",
    "nav.orders": "Orders",
    "nav.wishlist": "Wishlist",
    "nav.admin": "Admin",
    "nav.profile": "Profile",
    "nav.signIn": "Sign In",
    "nav.signOut": "Sign Out",
    "nav.adminPanel": "Admin Panel",
    "nav.kiutaCard": "Kiuta Card",

    // Hero
    "hero.badge": "Premium Electronics",
    "hero.title1": "Technology",
    "hero.title2": "reimagined.",
    "hero.desc1": "Curated selection of premium electronics.",
    "hero.desc2": "Minimal design. Maximum performance.",
    "hero.cta1": "Explore Catalog",
    "hero.cta2": "View Products",

    // Features
    "features.badge": "Why KIUTA",
    "features.title": "Built different.",
    "features.authentic.title": "Authentic Products",
    "features.authentic.desc": "Every item verified and sourced directly from manufacturers.",
    "features.delivery.title": "Express Delivery",
    "features.delivery.desc": "Free shipping on all orders. Delivered within 2-3 business days.",
    "features.support.title": "24/7 Support",
    "features.support.desc": "Dedicated support team ready to help you anytime.",
    "features.prices.title": "Best Prices",
    "features.prices.desc": "Competitive pricing with price-match guarantee on all items.",

    // Categories
    "categories.badge": "Browse",
    "categories.title": "Categories",
    "categories.viewAll": "View all",
    "categories.items": "items",

    // Products
    "products.badge": "Collection",
    "products.title": "Featured Products",
    "products.viewAll": "View all",
    "products.allBadge": "All",

    // Catalog
    "catalog.badge": "Browse",
    "catalog.title": "Catalog",
    "catalog.noProducts": "No products found",
    "catalog.tryDifferent": "Try selecting a different category above.",
    "catalog.cat.all": "All",
    "catalog.cat.smartphones": "Smartphones",
    "catalog.cat.laptops": "Laptops",
    "catalog.cat.audio": "Audio",
    "catalog.cat.wearables": "Wearables",
    "catalog.cat.accessories": "Accessories",
    "catalog.cat.cameras": "Cameras",

    // Product Card
    "product.add": "Add",
    "product.left": "left",
    "product.inStock": "In Stock",
    "product.outOfStock": "Out of Stock",
    "product.addToCart": "Add to Cart",
    "product.quantity": "Quantity",
    "product.category": "Category",
    "product.stock": "Stock",
    "product.shipping": "Shipping",
    "product.returns": "Returns",
    "product.free": "Free",
    "product.units": "units",
    "product.notFound": "Product not found",
    "product.notFoundDesc": "The product you're looking for doesn't exist or has been removed.",
    "product.backToProducts": "Back to products",

    // Product filters
    "filters.title": "Filters",
    "filters.search": "Search products",
    "filters.searchPlaceholder": "Search by name...",
    "filters.category": "Category",
    "filters.allCategories": "All categories",
    "filters.priceRange": "Price range",
    "filters.priceFrom": "From",
    "filters.priceTo": "To",
    "filters.inStockOnly": "In stock only",
    "filters.sortBy": "Sort by",
    "filters.sort.featured": "Featured",
    "filters.sort.priceAsc": "Price: low to high",
    "filters.sort.priceDesc": "Price: high to low",
    "filters.sort.nameAsc": "Name: A to Z",
    "filters.sort.nameDesc": "Name: Z to A",
    "filters.sort.newest": "Newest",
    "filters.clear": "Clear all",
    "filters.results": "results",
    "filters.noResults": "No products match your filters",
    "filters.noResultsDesc": "Try adjusting your search or filters",
    "filters.apply": "Apply",
    "filters.showFilters": "Show filters",
    "filters.hideFilters": "Hide filters",

    // Product detail enhancements
    "product.tabs.description": "Description",
    "product.tabs.specs": "Specifications",
    "product.tabs.shipping": "Shipping & Returns",
    "product.specs.sku": "SKU",
    "product.specs.brand": "Brand",
    "product.specs.warranty": "Warranty",
    "product.specs.weight": "Weight",
    "product.specs.dimensions": "Dimensions",
    "product.shippingDesc": "Free express shipping on all orders. Delivered within 2-3 business days. International shipping available.",
    "product.returnsDesc": "30-day return policy. Items must be in original condition with all accessories included.",
    "product.related": "You may also like",
    "product.share": "Share",
    "product.addedToCart": "Added to cart",
    "product.addedToWishlist": "Added to wishlist",
    "product.removedFromWishlist": "Removed from wishlist",
    "product.buyNow": "Buy now",
    "product.quantityLabel": "Qty",

    // Kiuta Card enhancements
    "kiutaCard.tiers": "Membership tiers",
    "kiutaCard.tier": "Tier",
    "kiutaCard.tier.free": "Free",
    "kiutaCard.tier.crystal": "Crystal",
    "kiutaCard.tier.black": "Black",
    "kiutaCard.currentTier": "Current tier",
    "kiutaCard.pointsToNext": "points to next tier",
    "kiutaCard.transactions": "Recent activity",
    "kiutaCard.transaction.earn": "Points earned",
    "kiutaCard.transaction.redeem": "Points redeemed",
    "kiutaCard.transaction.bonus": "Welcome bonus",
    "kiutaCard.faq.title": "Frequently asked questions",
    "kiutaCard.compare": "Compare tiers",
    "kiutaCard.perk": "Perk",
    "kiutaCard.upgrade": "Upgrade",

    // Store page enhancements
    "store.timeline": "Our journey",
    "store.timeline.2024": "Founded",
    "store.timeline.2024.desc": "KIUTA was born with a vision to redefine premium electronics retail.",
    "store.timeline.2025": "10K products",
    "store.timeline.2025.desc": "Reached 10,000 curated products and 50,000 happy customers.",
    "store.timeline.2026": "Global expansion",
    "store.timeline.2026.desc": "Launched international shipping with 100+ regions covered.",
    "store.team": "Meet the team",
    "store.team.desc": "The people behind KIUTA",
    "store.process": "How we work",
    "store.process.curate": "Curate",
    "store.process.curate.desc": "Hand-pick every product through rigorous testing.",
    "store.process.deliver": "Deliver",
    "store.process.deliver.desc": "Ship fast and safe from our global warehouses.",
    "store.process.support": "Support",
    "store.process.support.desc": "Stand behind every purchase with 24/7 care.",
    "store.faq.title": "Questions & answers",

    // Cart
    "cart.title": "Cart",
    "cart.empty": "Your cart is empty",
    "cart.continueShopping": "Continue shopping",
    "cart.total": "Total",
    "cart.checkout": "Checkout",

    // Wishlist
    "wishlist.title": "Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.emptyDesc": "Save items you love and come back to them later.",
    "wishlist.discover": "Discover Products",
    "wishlist.itemsSaved": "items saved",
    "wishlist.clearAll": "Clear all",
    "wishlist.moveToCart": "Add to Cart",
    "wishlist.addAllToCart": "Move all to cart",
    "wishlist.viewAll": "View all",

    // Checkout
    "checkout.badge": "Purchase",
    "checkout.title": "Checkout",
    "checkout.desc": "Review your order and complete your purchase.",
    "checkout.contact": "Contact information",
    "checkout.email": "Email",
    "checkout.fullName": "Full Name",
    "checkout.shipping": "Shipping address",
    "checkout.address": "Address",
    "checkout.city": "City",
    "checkout.zipCode": "ZIP Code",
    "checkout.placeOrder": "Place Order",
    "checkout.processing": "Processing…",
    "checkout.subtotal": "Subtotal",
    "checkout.shippingLabel": "Shipping",
    "checkout.shippingFree": "Free shipping on orders over $100",
    "checkout.item": "item",
    "checkout.items": "items",
    "checkout.empty": "Cart is empty",
    "checkout.emptyDesc": "Add some items to your cart before checking out.",
    "checkout.browseProducts": "Browse Products",
    "checkout.orderPlaced": "Order placed",
    "checkout.thankYou": "Thank you for your order. You'll receive a confirmation email shortly.",
    "checkout.viewOrders": "View Orders",
    "checkout.home": "Home",

    // Auth
    "auth.signIn": "Sign in",
    "auth.welcomeBack": "Welcome back. Enter your credentials.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.verifyEmail": "Verify email",
    "auth.noAccount": "No account?",
    "auth.signingIn": "Signing in…",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.createOne": "Create one",
    "auth.createAccount": "Create account",
    "auth.enterDetails": "Enter your details to get started.",
    "auth.name": "Name",
    "auth.confirmPassword": "Confirm password",
    "auth.minChars": "Minimum 8 characters",
    "auth.creatingAccount": "Creating account…",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.passwordsMatch": "Passwords do not match.",
    "auth.passwordLength": "Password must be at least 8 characters.",
    "auth.registrationFailed": "Registration failed. Please try again.",
    "auth.invalidLogin": "Invalid email or password. Please try again.",

    // OTP
    "otp.title": "Enter OTP",
    "otp.resetTitle": "Reset Password",
    "otp.sentTo": "We sent a 6-digit code to",
    "otp.enterCode": "Enter the 6-digit code sent to your email.",
    "otp.verify": "Verify Code",
    "otp.verifying": "Verifying...",
    "otp.resend": "Resend code",
    "otp.resendIn": "Resend in",
    "otp.backToSignIn": "← Back to Sign In",
    "otp.invalidCode": "Invalid code. Please try again.",
    "otp.somethingWrong": "Something went wrong.",
    "otp.resendFailed": "Failed to resend code.",

    // Verify
    "verify.title": "Verify Email",
    "verify.enterEmail": "Enter your email address and we'll send you a verification link.",
    "verify.sendLink": "Send Verification Link",
    "verify.sending": "Sending...",
    "verify.failed": "Failed to send verification email.",
    "verify.verifying": "Verifying...",
    "verify.pleaseWait": "Please wait a moment.",
    "verify.verified": "Email Verified",
    "verify.verifiedDesc": "Your email has been successfully verified.",
    "verify.continueSignIn": "Continue to Sign In",
    "verify.checkEmail": "Check Your Email",
    "verify.sentTo2": "We've sent a verification link to",
    "verify.backToSignIn": "Back to Sign In",
    "verify.invalidLink": "Verification link is invalid or expired.",

    // Profile
    "profile.badge": "Account",
    "profile.title": "Profile",
    "profile.manageAccount": "Manage your account settings",
    "profile.signOut": "Sign Out",
    "profile.notSignedIn": "Not signed in",
    "profile.notSignedInDesc": "Sign in to view and manage your profile.",
    "profile.noNameSet": "No name set",
    "profile.avatarUpdated": "Avatar updated",
    "profile.avatarUploadFailed": "Failed to upload avatar",
    "profile.idLabel": "ID",
    "profile.details": "Details",
    "profile.personalInfo": "Personal information",
    "profile.fullName": "Full Name",
    "profile.emailAddress": "Email Address",
    "profile.userId": "User ID",
    "profile.edit": "Edit",
    "profile.cancel": "Cancel",
    "profile.save": "Save",
    "profile.saved": "Profile updated successfully.",
    "profile.notSet": "Not set",
    "profile.enterName": "Enter your name",
    "profile.active": "Active",
    "profile.navigation": "Navigation",
    "profile.orderHistory": "Order History",
    "profile.viewPastOrders": "View past orders",
    "profile.savedItems": "Saved items",
    "profile.changeAvatar": "Change Avatar",
    "profile.removeAvatar": "Remove Avatar",

    // Orders
    "orders.badge": "Account",
    "orders.title": "Orders",
    "orders.desc": "View and track your order history.",
    "orders.notSignedIn": "Not signed in",
    "orders.notSignedInDesc": "Sign in to view your order history.",
    "orders.noOrders": "No orders yet",
    "orders.noOrdersDesc": "Your order history will appear here once you make a purchase.",
    "orders.browseProducts": "Browse Products",
    "orders.failedToLoad": "Failed to load orders. Please try again later.",
    "orders.total": "Total",
    "orders.qty": "Qty",

    // Status
    "status.pending": "Pending",
    "status.processing": "Processing",
    "status.shipped": "Shipped",
    "status.delivered": "Delivered",
    "status.cancelled": "Cancelled",

    // Footer
    "footer.shop": "Shop",
    "footer.account": "Account",
    "footer.info": "Info",
    "footer.about": "About",
    "footer.shipping": "Shipping",
    "footer.returns": "Returns",
    "footer.contact": "Contact",
    "footer.crystalPowered": "crystal-powered",
    "footer.rights": "All rights reserved.",
    "footer.desc": "Premium electronics marketplace. Curated for the modern lifestyle.",
    "footer.catalog": "Catalog",
    "footer.products": "Products",
    "footer.kiutaCard": "Kiuta Card",
    "footer.profile": "Profile",
    "footer.orders": "Orders",
    "footer.wishlist": "Wishlist",
    "footer.signIn": "Sign In",

    // Stats
    "stats.products": "Products",
    "stats.customers": "Customers",
    "stats.satisfaction": "Satisfaction",
    "stats.support": "Support",

    // Showcase
    "showcase.badge": "Why us",
    "showcase.title": "Engineered for excellence",
    "showcase.subtitle": "Every detail is crafted to deliver a premium experience from browsing to unboxing.",
    "showcase.fast.title": "Lightning fast",
    "showcase.fast.desc": "Server-rendered pages and edge CDN deliver content in milliseconds, anywhere on the globe.",
    "showcase.secure.title": "Bank-grade security",
    "showcase.secure.desc": "JWT authentication, bcrypt hashing, and TLS encryption keep your data locked down at every layer.",
    "showcase.global.title": "Globally available",
    "showcase.global.desc": "Deployed on Vercel's edge network with 100+ regions. Your store is always close to your customers.",
    "showcase.cta1": "Browse catalog",
    "showcase.cta2": "Our story",

    // CTA
    "cta.badge": "Ready to begin",
    "cta.title": "Step into the future of premium tech",
    "cta.desc": "Join thousands of customers who trust KIUTA for authentic, premium electronics delivered fast.",
    "cta.button1": "Start shopping",
    "cta.button2": "Learn more",

    // Marquee
    "marquee.title": "Trusted brands we carry",

    // Store page
    "store.badge": "About Us",
    "store.title": "The KIUTA",
    "store.subtitle": "experience.",
    "store.desc": "We believe technology should be beautiful, intuitive, and accessible. KIUTA is more than a store — it's a curated space for those who appreciate the intersection of design and innovation.",
    "store.ourValues": "Our Values",
    "store.contact": "Contact",
    "store.products": "Products",
    "store.customers": "Customers",
    "store.satisfaction": "Satisfaction",
    "store.support": "Support",
    "store.values.curated.title": "Curated Selection",
    "store.values.curated.desc": "Every product in our catalog is hand-picked and rigorously tested. We don't list anything we wouldn't use ourselves.",
    "store.values.pricing.title": "Transparent Pricing",
    "store.values.pricing.desc": "No hidden fees, no artificial markups. Our prices reflect the true value of premium electronics.",
    "store.values.compromise.title": "Zero Compromise",
    "store.values.compromise.desc": "From packaging to delivery, every touchpoint is designed to match the quality of the products we sell.",
    "store.getInTouch": "Get in Touch",
    "store.touchDesc": "Have a question about an order, a product, or just want to say hello? We're here for you.",
    "store.emailLabel": "Email",
    "store.hoursLabel": "Hours",
    "store.locationLabel": "Location",
    "store.whatDrivesUs": "What drives us",

    // Kiuta Card
    "kiutaCard.badge": "Membership",
    "kiutaCard.title": "KIUTA Card",
    "kiutaCard.desc": "Your premium membership card. Unlock exclusive benefits and earn points on every purchase.",
    "kiutaCard.cardholder": "Cardholder",
    "kiutaCard.points": "Points",
    "kiutaCard.nextTier": "Next tier",
    "kiutaCard.benefits.title": "Membership Benefits",
    "kiutaCard.benefits.perks": "Perks",
    "kiutaCard.freeShipping": "Free Shipping",
    "kiutaCard.freeShippingDesc": "On all orders, always.",
    "kiutaCard.earlyAccess": "Early Access",
    "kiutaCard.earlyAccessDesc": "Get new products before anyone else.",
    "kiutaCard.exclusiveDeals": "Exclusive Deals",
    "kiutaCard.exclusiveDealsDesc": "Members-only pricing on select items.",
    "kiutaCard.prioritySupport": "Priority Support",
    "kiutaCard.prioritySupportDesc": "Skip the queue with dedicated help.",
    "kiutaCard.extendedReturns": "Extended Returns",
    "kiutaCard.extendedReturnsDesc": "60-day return window.",
    "kiutaCard.birthdayRewards": "Birthday Rewards",
    "kiutaCard.birthdayRewardsDesc": "Special discounts on your birthday.",
    "kiutaCard.guestMember": "Guest Member",
    "kiutaCard.signInToView": "Sign In to View Your Card",

    // Breadcrumbs
    "breadcrumbs.home": "Home",

    // Language
    "lang.en": "EN",
    "lang.ru": "RU",
  },
  ru: {
    // Header
    "nav.catalog": "Каталог",
    "nav.products": "Товары",
    "nav.store": "Магазин",
    "nav.orders": "Заказы",
    "nav.wishlist": "Избранное",
    "nav.admin": "Админ",
    "nav.profile": "Профиль",
    "nav.signIn": "Войти",
    "nav.signOut": "Выйти",
    "nav.adminPanel": "Панель администратора",
    "nav.kiutaCard": "Карта KIUTA",

    // Hero
    "hero.badge": "Премиум электроника",
    "hero.title1": "Технологии",
    "hero.title2": "переосмыслены.",
    "hero.desc1": "Тщательно отобранная коллекция премиальной электроники.",
    "hero.desc2": "Минималистичный дизайн. Максимальная производительность.",
    "hero.cta1": "Перейти в каталог",
    "hero.cta2": "Смотреть товары",

    // Features
    "features.badge": "Почему KIUTA",
    "features.title": "Созданы иначе.",
    "features.authentic.title": "Подлинные товары",
    "features.authentic.desc": "Каждый товар проверен и поставлен напрямую от производителей.",
    "features.delivery.title": "Быстрая доставка",
    "features.delivery.desc": "Бесплатная доставка всех заказов. Доставка за 2-3 рабочих дня.",
    "features.support.title": "Поддержка 24/7",
    "features.support.desc": "Команда поддержки готова помочь вам в любое время.",
    "features.prices.title": "Лучшие цены",
    "features.prices.desc": "Конкурентные цены с гарантией соответствия цен на все товары.",

    // Categories
    "categories.badge": "Просмотр",
    "categories.title": "Категории",
    "categories.viewAll": "Смотреть все",
    "categories.items": "товаров",

    // Products
    "products.badge": "Коллекция",
    "products.title": "Рекомендуемые товары",
    "products.viewAll": "Смотреть все",
    "products.allBadge": "Все",

    // Catalog
    "catalog.badge": "Просмотр",
    "catalog.title": "Каталог",
    "catalog.noProducts": "Товары не найдены",
    "catalog.tryDifferent": "Попробуйте выбрать другую категорию выше.",
    "catalog.cat.all": "Все",
    "catalog.cat.smartphones": "Смартфоны",
    "catalog.cat.laptops": "Ноутбуки",
    "catalog.cat.audio": "Аудио",
    "catalog.cat.wearables": "Носимые устройства",
    "catalog.cat.accessories": "Аксессуары",
    "catalog.cat.cameras": "Камеры",

    // Product Card
    "product.add": "Добавить",
    "product.left": "осталось",
    "product.inStock": "В наличии",
    "product.outOfStock": "Нет в наличии",
    "product.addToCart": "В корзину",
    "product.quantity": "Количество",
    "product.category": "Категория",
    "product.stock": "На складе",
    "product.shipping": "Доставка",
    "product.returns": "Возвраты",
    "product.free": "Бесплатно",
    "product.units": "шт.",
    "product.notFound": "Товар не найден",
    "product.notFoundDesc": "Товар, который вы ищете, не существует или был удалён.",
    "product.backToProducts": "Назад к товарам",

    // Product filters
    "filters.title": "Фильтры",
    "filters.search": "Поиск товаров",
    "filters.searchPlaceholder": "Поиск по названию...",
    "filters.category": "Категория",
    "filters.allCategories": "Все категории",
    "filters.priceRange": "Диапазон цен",
    "filters.priceFrom": "От",
    "filters.priceTo": "До",
    "filters.inStockOnly": "Только в наличии",
    "filters.sortBy": "Сортировка",
    "filters.sort.featured": "Рекомендуемые",
    "filters.sort.priceAsc": "Цена: по возрастанию",
    "filters.sort.priceDesc": "Цена: по убыванию",
    "filters.sort.nameAsc": "Название: А-Я",
    "filters.sort.nameDesc": "Название: Я-А",
    "filters.sort.newest": "Новинки",
    "filters.clear": "Сбросить всё",
    "filters.results": "результатов",
    "filters.noResults": "Нет товаров по вашим фильтрам",
    "filters.noResultsDesc": "Попробуйте изменить поиск или фильтры",
    "filters.apply": "Применить",
    "filters.showFilters": "Показать фильтры",
    "filters.hideFilters": "Скрыть фильтры",

    // Product detail enhancements
    "product.tabs.description": "Описание",
    "product.tabs.specs": "Характеристики",
    "product.tabs.shipping": "Доставка и возврат",
    "product.specs.sku": "Артикул",
    "product.specs.brand": "Бренд",
    "product.specs.warranty": "Гарантия",
    "product.specs.weight": "Вес",
    "product.specs.dimensions": "Габариты",
    "product.shippingDesc": "Бесплатная экспресс-доставка на все заказы. Доставка в течение 2-3 рабочих дней. Международная доставка доступна.",
    "product.returnsDesc": "Политика возврата 30 дней. Товары должны быть в оригинальном состоянии со всеми комплектующими.",
    "product.related": "Вам также понравится",
    "product.share": "Поделиться",
    "product.addedToCart": "Добавлено в корзину",
    "product.addedToWishlist": "Добавлено в избранное",
    "product.removedFromWishlist": "Удалено из избранного",
    "product.buyNow": "Купить сейчас",
    "product.quantityLabel": "Кол-во",

    // Kiuta Card enhancements
    "kiutaCard.tiers": "Уровни членства",
    "kiutaCard.tier": "Уровень",
    "kiutaCard.tier.free": "Free",
    "kiutaCard.tier.crystal": "Crystal",
    "kiutaCard.tier.black": "Black",
    "kiutaCard.currentTier": "Текущий уровень",
    "kiutaCard.pointsToNext": "баллов до следующего уровня",
    "kiutaCard.transactions": "Недавняя активность",
    "kiutaCard.transaction.earn": "Баллы начислены",
    "kiutaCard.transaction.redeem": "Баллы списаны",
    "kiutaCard.transaction.bonus": "Приветственный бонус",
    "kiutaCard.faq.title": "Часто задаваемые вопросы",
    "kiutaCard.compare": "Сравнить уровни",
    "kiutaCard.perk": "Привилегия",
    "kiutaCard.upgrade": "Повысить",

    // Store page enhancements
    "store.timeline": "Наш путь",
    "store.timeline.2024": "Основание",
    "store.timeline.2024.desc": "KIUTA зародился с миссией переосмыслить розничную продажу премиум-электроники.",
    "store.timeline.2025": "10K товаров",
    "store.timeline.2025.desc": "Достигли 10 000 отобранных товаров и 50 000 довольных клиентов.",
    "store.timeline.2026": "Глобальное расширение",
    "store.timeline.2026.desc": "Запустили международную доставку в 100+ регионов.",
    "store.team": "Наша команда",
    "store.team.desc": "Люди, стоящие за KIUTA",
    "store.process": "Как мы работаем",
    "store.process.curate": "Отбор",
    "store.process.curate.desc": "Вручную отбираем каждый товар через тщательное тестирование.",
    "store.process.deliver": "Доставка",
    "store.process.deliver.desc": "Отправляем быстро и безопасно с наших глобальных складов.",
    "store.process.support": "Поддержка",
    "store.process.support.desc": "Отвечаем за каждую покупку с заботой 24/7.",
    "store.faq.title": "Вопросы и ответы",

    // Cart
    "cart.title": "Корзина",
    "cart.empty": "Ваша корзина пуста",
    "cart.continueShopping": "Продолжить покупки",
    "cart.total": "Итого",
    "cart.checkout": "Оформить заказ",

    // Wishlist
    "wishlist.title": "Избранное",
    "wishlist.empty": "Ваш список желаний пуст",
    "wishlist.emptyDesc": "Сохраняйте понравившиеся товары и возвращайтесь к ним позже.",
    "wishlist.discover": "Открыть товары",
    "wishlist.itemsSaved": "сохранено",
    "wishlist.clearAll": "Очистить всё",
    "wishlist.moveToCart": "В корзину",
    "wishlist.addAllToCart": "Переместить всё в корзину",
    "wishlist.viewAll": "Смотреть всё",

    // Checkout
    "checkout.badge": "Покупка",
    "checkout.title": "Оформление заказа",
    "checkout.desc": "Проверьте заказ и завершите покупку.",
    "checkout.contact": "Контактная информация",
    "checkout.email": "Эл. почта",
    "checkout.fullName": "Полное имя",
    "checkout.shipping": "Адрес доставки",
    "checkout.address": "Адрес",
    "checkout.city": "Город",
    "checkout.zipCode": "Почтовый индекс",
    "checkout.placeOrder": "Оформить заказ",
    "checkout.processing": "Обработка…",
    "checkout.subtotal": "Подитог",
    "checkout.shippingLabel": "Доставка",
    "checkout.shippingFree": "Бесплатная доставка при заказе от $100",
    "checkout.item": "товар",
    "checkout.items": "товаров",
    "checkout.empty": "Корзина пуста",
    "checkout.emptyDesc": "Добавьте товары в корзину перед оформлением заказа.",
    "checkout.browseProducts": "Перейти к товарам",
    "checkout.orderPlaced": "Заказ оформлен",
    "checkout.thankYou": "Спасибо за ваш заказ. Вы получите подтверждение по электронной почте.",
    "checkout.viewOrders": "Мои заказы",
    "checkout.home": "Главная",

    // Auth
    "auth.signIn": "Вход",
    "auth.welcomeBack": "С возвращением. Введите свои данные.",
    "auth.email": "Эл. почта",
    "auth.password": "Пароль",
    "auth.verifyEmail": "Подтвердить почту",
    "auth.noAccount": "Нет аккаунта?",
    "auth.signingIn": "Входим…",
    "auth.dontHaveAccount": "Нет аккаунта?",
    "auth.createOne": "Создать",
    "auth.createAccount": "Создать аккаунт",
    "auth.enterDetails": "Введите свои данные для начала.",
    "auth.name": "Имя",
    "auth.confirmPassword": "Подтвердите пароль",
    "auth.minChars": "Минимум 8 символов",
    "auth.creatingAccount": "Создание аккаунта…",
    "auth.alreadyHaveAccount": "Уже есть аккаунт?",
    "auth.passwordsMatch": "Пароли не совпадают.",
    "auth.passwordLength": "Пароль должен содержать не менее 8 символов.",
    "auth.registrationFailed": "Ошибка регистрации. Попробуйте снова.",
    "auth.invalidLogin": "Неверный email или пароль. Попробуйте снова.",

    // OTP
    "otp.title": "Введите OTP",
    "otp.resetTitle": "Сброс пароля",
    "otp.sentTo": "Мы отправили 6-значный код на",
    "otp.enterCode": "Введите 6-значный код, отправленный на вашу электронную почту.",
    "otp.verify": "Подтвердить код",
    "otp.verifying": "Проверка...",
    "otp.resend": "Отправить повторно",
    "otp.resendIn": "Повторная отправка через",
    "otp.backToSignIn": "← Назад к входу",
    "otp.invalidCode": "Неверный код. Попробуйте снова.",
    "otp.somethingWrong": "Что-то пошло не так.",
    "otp.resendFailed": "Не удалось отправить код повторно.",

    // Verify
    "verify.title": "Подтверждение email",
    "verify.enterEmail": "Введите адрес электронной почты, и мы отправим вам ссылку для подтверждения.",
    "verify.sendLink": "Отправить ссылку",
    "verify.sending": "Отправка...",
    "verify.failed": "Не удалось отправить письмо для подтверждения.",
    "verify.verifying": "Проверка...",
    "verify.pleaseWait": "Пожалуйста, подождите.",
    "verify.verified": "Email подтверждён",
    "verify.verifiedDesc": "Ваш email успешно подтверждён.",
    "verify.continueSignIn": "Перейти ко входу",
    "verify.checkEmail": "Проверьте почту",
    "verify.sentTo2": "Мы отправили ссылку для подтверждения на",
    "verify.backToSignIn": "Назад ко входу",
    "verify.invalidLink": "Ссылка для подтверждения недействительна или истёк срок действия.",

    // Profile
    "profile.badge": "Аккаунт",
    "profile.title": "Профиль",
    "profile.manageAccount": "Управляйте настройками аккаунта",
    "profile.signOut": "Выйти",
    "profile.notSignedIn": "Вы не вошли",
    "profile.notSignedInDesc": "Войдите, чтобы просмотреть и управлять профилем.",
    "profile.noNameSet": "Имя не указано",
    "profile.avatarUpdated": "Аватар обновлён",
    "profile.avatarUploadFailed": "Не удалось загрузить аватар",
    "profile.idLabel": "ID",
    "profile.details": "Данные",
    "profile.personalInfo": "Личная информация",
    "profile.fullName": "Полное имя",
    "profile.emailAddress": "Адрес электронной почты",
    "profile.userId": "ID пользователя",
    "profile.edit": "Изменить",
    "profile.cancel": "Отмена",
    "profile.save": "Сохранить",
    "profile.saved": "Профиль успешно обновлён.",
    "profile.notSet": "Не указано",
    "profile.enterName": "Введите ваше имя",
    "profile.active": "Активен",
    "profile.navigation": "Навигация",
    "profile.orderHistory": "История заказов",
    "profile.viewPastOrders": "Просмотр прошлых заказов",
    "profile.savedItems": "Сохранённые товары",
    "profile.changeAvatar": "Изменить аватар",
    "profile.removeAvatar": "Удалить аватар",

    // Orders
    "orders.badge": "Аккаунт",
    "orders.title": "Заказы",
    "orders.desc": "Просмотрите и отследьте историю заказов.",
    "orders.notSignedIn": "Вы не вошли",
    "orders.notSignedInDesc": "Войдите, чтобы просмотреть историю заказов.",
    "orders.noOrders": "Заказов пока нет",
    "orders.noOrdersDesc": "Ваша история заказов появится здесь после первой покупки.",
    "orders.browseProducts": "Перейти к товарам",
    "orders.failedToLoad": "Не удалось загрузить заказы. Попробуйте позже.",
    "orders.total": "Итого",
    "orders.qty": "Кол-во",

    // Status
    "status.pending": "Ожидает",
    "status.processing": "Обработка",
    "status.shipped": "Отправлен",
    "status.delivered": "Доставлен",
    "status.cancelled": "Отменён",

    // Footer
    "footer.shop": "Магазин",
    "footer.account": "Аккаунт",
    "footer.info": "Информация",
    "footer.about": "О нас",
    "footer.shipping": "Доставка",
    "footer.returns": "Возвраты",
    "footer.contact": "Контакты",
    "footer.crystalPowered": "crystal-powered",
    "footer.rights": "Все права защищены.",
    "footer.desc": "Маркетплейс премиальной электроники. Курируется для современного образа жизни.",
    "footer.catalog": "Каталог",
    "footer.products": "Товары",
    "footer.kiutaCard": "Карта KIUTA",
    "footer.profile": "Профиль",
    "footer.orders": "Заказы",
    "footer.wishlist": "Избранное",
    "footer.signIn": "Войти",

    // Stats
    "stats.products": "Товаров",
    "stats.customers": "Клиентов",
    "stats.satisfaction": "Удовлетворённость",
    "stats.support": "Поддержка",

    // Showcase
    "showcase.badge": "Почему мы",
    "showcase.title": "Создано для совершенства",
    "showcase.subtitle": "Каждая деталь продумана, чтобы обеспечить премиальный опыт — от просмотра до распаковки.",
    "showcase.fast.title": "Молниеносная скорость",
    "showcase.fast.desc": "Серверный рендеринг и edge-CDN доставляют контент за миллисекунды в любую точку мира.",
    "showcase.secure.title": "Безопасность уровня банка",
    "showcase.secure.desc": "JWT-аутентификация, bcrypt-хэширование и TLS-шифрование защищают данные на каждом уровне.",
    "showcase.global.title": "Глобальная доступность",
    "showcase.global.desc": "Развёртывание на edge-сети Vercel со 100+ регионами. Ваш магазин всегда близко к покупателям.",
    "showcase.cta1": "Открыть каталог",
    "showcase.cta2": "О нас",

    // CTA
    "cta.badge": "Готовы начать",
    "cta.title": "Шагните в будущее премиум-техники",
    "cta.desc": "Присоединяйтесь к тысячам покупателей, которые доверяют KIUTA оригинальную премиум-электронику с быстрой доставкой.",
    "cta.button1": "Начать покупки",
    "cta.button2": "Узнать больше",

    // Marquee
    "marquee.title": "Бренды, которым доверяют",

    // Store page
    "store.badge": "О нас",
    "store.title": "Опыт",
    "store.subtitle": "KIUTA.",
    "store.desc": "Мы верим, что технологии должны быть красивыми, интуитивными и доступными. KIUTA — это больше, чем магазин. Это курируемое пространство для тех, кто ценит пересечение дизайна и инноваций.",
    "store.ourValues": "Наши ценности",
    "store.contact": "Контакты",
    "store.products": "Товаров",
    "store.customers": "Клиентов",
    "store.satisfaction": "Удовлетворённость",
    "store.support": "Поддержка",
    "store.values.curated.title": "Тщательный отбор",
    "store.values.curated.desc": "Каждый товар в нашем каталоге вручную отобран и тщательно протестирован. Мы не размещаем ничего, чем не пользовались бы сами.",
    "store.values.pricing.title": "Прозрачные цены",
    "store.values.pricing.desc": "Никаких скрытых сборов, никаких искусственных наценок. Наши цены отражают истинную стоимость премиальной электроники.",
    "store.values.compromise.title": "Ноль компромиссов",
    "store.values.compromise.desc": "От упаковки до доставки — каждая деталь спроектирована для соответствия качеству продаваемых товаров.",
    "store.getInTouch": "Свяжитесь с нами",
    "store.touchDesc": "Есть вопрос о заказе, товаре или просто хотите поздороваться? Мы всегда на связи.",
    "store.emailLabel": "Email",
    "store.hoursLabel": "Часы работы",
    "store.locationLabel": "Адрес",
    "store.whatDrivesUs": "Что нами движет",

    // Kiuta Card
    "kiutaCard.badge": "Членство",
    "kiutaCard.title": "Карта KIUTA",
    "kiutaCard.desc": "Ваша премиальная карточка членства. Откройте эксклюзивные преимущества и получайте баллы за каждую покупку.",
    "kiutaCard.cardholder": "Владелец карты",
    "kiutaCard.points": "Баллы",
    "kiutaCard.nextTier": "Следующий уровень",
    "kiutaCard.benefits.title": "Преимущества членства",
    "kiutaCard.benefits.perks": "Привилегии",
    "kiutaCard.freeShipping": "Бесплатная доставка",
    "kiutaCard.freeShippingDesc": "Все заказы — всегда бесплатно.",
    "kiutaCard.earlyAccess": "Ранний доступ",
    "kiutaCard.earlyAccessDesc": "Получайте новые товары раньше всех.",
    "kiutaCard.exclusiveDeals": "Эксклюзивные скидки",
    "kiutaCard.exclusiveDealsDesc": "Специальные цены для участников на выбранные товары.",
    "kiutaCard.prioritySupport": "Приоритетная поддержка",
    "kiutaCard.prioritySupportDesc": "Пропустите очередь с выделенной помощью.",
    "kiutaCard.extendedReturns": "Продлённые возвраты",
    "kiutaCard.extendedReturnsDesc": "Возврат в течение 60 дней.",
    "kiutaCard.birthdayRewards": "Подарки на день рождения",
    "kiutaCard.birthdayRewardsDesc": "Специальные скидки в ваш день рождения.",
    "kiutaCard.guestMember": "Гость",
    "kiutaCard.signInToView": "Войдите для просмотра карты",

    // Breadcrumbs
    "breadcrumbs.home": "Главная",

    // Language
    "lang.en": "EN",
    "lang.ru": "RU",
  },
};

export const useLanguage = create<LanguageState>()(
  persist(
    (set, get) => ({
      lang: "ru",
      setLang: (lang: Language) => set({ lang }),
      t: (key: string) => {
        const { lang } = get();
        return translations[lang][key] || translations["en"][key] || key;
      },
    }),
    { name: "kiuta-lang" },
  ),
);